-- ============================================================================
-- 1. DATABASE & SCHEMA SETUP
-- ============================================================================
CREATE DATABASE IF NOT EXISTS IPL_MDM;
USE DATABASE IPL_MDM;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;

-- ============================================================================
-- 2. BRONZE LAYER: RAW DATA INGESTION
-- ============================================================================
USE SCHEMA BRONZE;

-- Create Raw Deliveries Table
CREATE OR REPLACE TABLE BRONZE.RAW_DELIVERIES (
    MATCH_ID NUMBER,INNING  NUMBER,BATTING_TEAM  VARCHAR(100),
    BOWLING_TEAM VARCHAR(100),OVER   NUMBER,BALL  NUMBER,
    BATTER  VARCHAR(100),BOWLER  VARCHAR(100),NON_STRIKER VARCHAR(100),BATSMAN_RUNS  NUMBER,
    EXTRA_RUNS   NUMBER,TOTAL_RUNS NUMBER,EXTRAS_TYPE  VARCHAR(50),IS_WICKET NUMBER,
    PLAYER_DISMISSED VARCHAR(100),DISMISSAL_KIND  VARCHAR(100),FIELDER   VARCHAR(100)
);

-- Create Stage for CSV Loading
CREATE OR REPLACE STAGE IPL_MDM.BRONZE.IPL_STAGE

FILE_FORMAT = (
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
NULL_IF = ('NA', 'N/A', '', 'NULL')
EMPTY_FIELD_AS_NULL = TRUE
FIELD_DELIMITER = ','
);

LIST @IPL_MDM.BRONZE.IPL_STAGE;

-- Copy Data from Stage into Bronze Table
COPY INTO IPL_MDM.BRONZE.RAW_DELIVERIES
FROM @IPL_MDM.BRONZE.IPL_STAGE/deliveries.csv
FILE_FORMAT = (
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
NULL_IF = ('NA', 'N/A', '', 'NULL')
EMPTY_FIELD_AS_NULL = TRUE
FIELD_DELIMITER = ','

);

-- Verify Bronze Load
SELECT COUNT(*) AS BRONZE_ROWS FROM IPL_MDM.BRONZE.RAW_DELIVERIES;


-- ============================================================================
-- 3. SILVER LAYER: TRANFORMATION & CLEANING
-- ============================================================================

USE SCHEMA SILVER;

CREATE OR REPLACE TABLE IPL_MDM.SILVER.CLEAN_DELIVERIES AS 
SELECT 
    MATCH_ID, 
    INNING, 
    BATTING_TEAM, 
    BOWLING_TEAM, 
    OVER + 1 AS OVER_NUMBER, 
    BALL, 
    BATTER, 
    BOWLER, 
    NON_STRIKER, 
    BATSMAN_RUNS, 
    EXTRA_RUNS, 
    TOTAL_RUNS, 
    CASE WHEN EXTRAS_TYPE IS NULL OR EXTRAS_TYPE = '' THEN 'NO_EXTRA' ELSE UPPER(EXTRAS_TYPE) END AS EXTRAS_TYPE, 
    IS_WICKET, 
    CASE WHEN PLAYER_DISMISSED IS NULL THEN 'NOT_DISMISSED' ELSE PLAYER_DISMISSED END AS PLAYER_DISMISSED, 
    CASE WHEN DISMISSAL_KIND IS NULL THEN 'NOT_DISMISSED' ELSE UPPER(DISMISSAL_KIND) END AS DISMISSAL_KIND, 
    CASE WHEN FIELDER IS NULL THEN 'NOT_APPLICABLE' ELSE FIELDER END AS FIELDER, 
    CASE WHEN EXTRA_RUNS > 0 THEN 'YES' ELSE 'NO' END AS IS_EXTRA, 
    CASE 
        WHEN BATTING_TEAM = 'Deccan Chargers' THEN 'Sunrisers Hyderabad' 
        WHEN BATTING_TEAM = 'Delhi Daredevils' THEN 'Delhi Capitals' 
        WHEN BATTING_TEAM = 'Kings XI Punjab' THEN 'Punjab Kings' 
        WHEN BATTING_TEAM = 'Rising Pune Supergiant' THEN 'Rising Pune Supergiants' 
        ELSE BATTING_TEAM 
    END AS BATTING_TEAM_STANDARD, 
    CASE 
        WHEN BOWLING_TEAM = 'Deccan Chargers' THEN 'Sunrisers Hyderabad' 
        WHEN BOWLING_TEAM = 'Delhi Daredevils' THEN 'Delhi Capitals' 
        WHEN BOWLING_TEAM = 'Kings XI Punjab' THEN 'Punjab Kings' 
        WHEN BOWLING_TEAM = 'Rising Pune Supergiant' THEN 'Rising Pune Supergiants' 
        ELSE BOWLING_TEAM 
    END AS BOWLING_TEAM_STANDARD, 
    CONCAT(MATCH_ID, '-', INNING, '-', OVER + 1, '-', BALL) AS BALL_ID
FROM IPL_MDM.BRONZE.RAW_DELIVERIES; 

-- Verification Queries for Silver Layer
SELECT COUNT(*) AS SILVER_ROWS FROM IPL_MDM.SILVER.CLEAN_DELIVERIES;
SELECT * FROM IPL_MDM.SILVER.CLEAN_DELIVERIES LIMIT 10;

SELECT EXTRAS_TYPE, COUNT(*) AS COUNT
FROM IPL_MDM.SILVER.CLEAN_DELIVERIES
GROUP BY EXTRAS_TYPE
ORDER BY COUNT DESC;

-- ============================================================================
-- 4. GOLD LAYER: PERFORMANCE SUMMARIES
-- ============================================================================
USE SCHEMA GOLD;

--GOLD TABLE 1 - TEAM PERFORMANCE SUMMARY
CREATE OR REPLACE TABLE IPL_MDM.GOLD.TEAM_PERFORMANCE AS
SELECT
    BATTING_TEAM_STANDARD          AS TEAM,
    COUNT(DISTINCT MATCH_ID)       AS MATCHES_PLAYED,
    SUM(BATSMAN_RUNS)              AS TOTAL_BATSMAN_RUNS,
    SUM(EXTRA_RUNS)                AS TOTAL_EXTRA_RUNS,
    SUM(TOTAL_RUNS)                AS TOTAL_RUNS_SCORED,
    SUM(IS_WICKET)                 AS TOTAL_WICKETS_LOST,
    ROUND(SUM(TOTAL_RUNS) / NULLIF(COUNT(DISTINCT MATCH_ID), 0), 2) AS AVG_RUNS_PER_MATCH
FROM IPL_MDM.SILVER.CLEAN_DELIVERIES
GROUP BY BATTING_TEAM_STANDARD
ORDER BY TOTAL_RUNS_SCORED DESC;


-- GOLD TABLE 2 - BOWLER PERFORMANCE SUMMARY
CREATE OR REPLACE TABLE IPL_MDM.GOLD.BOWLER_PERFORMANCE AS
SELECT
    BOWLER,
    COUNT(DISTINCT MATCH_ID)  AS MATCHES_PLAYED,
    COUNT(*)                  AS BALLS_BOWLED,
    SUM(TOTAL_RUNS)           AS RUNS_CONCEDED,
    SUM(IS_WICKET)            AS WICKETS_TAKEN,
    ROUND(SUM(TOTAL_RUNS) / NULLIF(SUM(IS_WICKET), 0), 2) AS BOWLING_AVERAGE,
    ROUND(COUNT(*) / NULLIF(SUM(IS_WICKET), 0), 2)        AS STRIKE_RATE
FROM IPL_MDM.SILVER.CLEAN_DELIVERIES
GROUP BY BOWLER
ORDER BY WICKETS_TAKEN DESC;


-- GOLD TABLE 3 - BATTER PERFORMANCE SUMMARY
CREATE OR REPLACE TABLE IPL_MDM.GOLD.BATTER_PERFORMANCE AS
SELECT
    BATTER,
    COUNT(DISTINCT MATCH_ID)       AS MATCHES_PLAYED,
    SUM(BATSMAN_RUNS)              AS TOTAL_RUNS,
    COUNT(*)                       AS BALLS_FACED,
    SUM(IS_WICKET)                 AS TIMES_DISMISSED,
    ROUND(SUM(BATSMAN_RUNS) / NULLIF(SUM(IS_WICKET), 0), 2)        AS BATTING_AVERAGE,
    ROUND((SUM(BATSMAN_RUNS) / NULLIF(COUNT(*), 0)) * 100, 2)      AS STRIKE_RATE,
    MAX(BATSMAN_RUNS)                               AS HIGHEST_SCORE_IN_A_BALL
FROM IPL_MDM.SILVER.CLEAN_DELIVERIES
GROUP BY BATTER
ORDER BY TOTAL_RUNS DESC;

--VERIFY GOLD TABLE 1 - TEAM PERFORMANCE
SELECT * FROM IPL_MDM.GOLD.TEAM_PERFORMANCE LIMIT 10;

--VERIFY GOLD TABLE 2 - BOWLER PERFORMANCE
SELECT * FROM IPL_MDM.GOLD.BOWLER_PERFORMANCE LIMIT 10;

--VERIFY GOLD TABLE 3 - BATTER PERFORMANCE
SELECT * FROM IPL_MDM.GOLD.BATTER_PERFORMANCE LIMIT 10;


-- ============================================================================
-- 3. PIPELINE AUDIT: DATA LAYER ROW COUNTS
-- ============================================================================
SELECT 'BRONZE' AS LAYER, COUNT(*) AS ROW_COUNT FROM IPL_MDM.BRONZE.RAW_DELIVERIES
UNION ALL
SELECT 'SILVER' AS LAYER, COUNT(*) AS ROW_COUNT FROM IPL_MDM.SILVER.CLEAN_DELIVERIES
UNION ALL
SELECT 'GOLD - TEAM' AS LAYER, COUNT(*) AS ROW_COUNT FROM IPL_MDM.GOLD.TEAM_PERFORMANCE
UNION ALL
SELECT 'GOLD - BOWLER' AS LAYER, COUNT(*) AS ROW_COUNT FROM IPL_MDM.GOLD.BOWLER_PERFORMANCE
UNION ALL
SELECT 'GOLD - BATTER' AS LAYER, COUNT(*) AS ROW_COUNT FROM IPL_MDM.GOLD.BATTER_PERFORMANCE;